version: "3"
services:
  web:
    build: ./api
    networks:
      - sample_network
    container_name: "liquor-api"
    volumes:
      - ./api:/usr/src/api
    ports:
      - "8080:8080"
    tty: true
  db:
    build: ./dbserver
    networks:
      - sample_network
    container_name: "liquor-mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: liquor
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./dbserver/data:/var/lib/mysql
      - ./dbserver/conf/my.cnf:/etc/my.cnf
    ports:
      - 3306:3306

networks:
  sample_network:
