version: "3"
services:
  web:
    build: .
    container_name: "liquor-api-dev"
    volumes:
      - ../api:/usr/src/api
    ports:
      - "8080:8080"
    tty: true
  db:
    build: ../dbserver
    container_name: "liquor-mysql-dev"
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: liquor
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ../dbserver/data:/var/lib/mysql
      - ../dbserver/conf/my.cnf:/etc/my.cnf
    ports:
      - 3306:3306