GET http://localhost:8080/hello
###
//カクテル一覧を検索
GET http://localhost:8080/cocktails/
###
//材料一覧を検索
GET http://localhost:8080/ingredients/
###
//特定のカクテルの情報を検索
GET http://localhost:8080/cocktail/ジントニック
###
//特定の材料を使うカクテル一覧を検索
GET http://localhost:8080/cocktails/ドライジン

###
//エラーチェック
GET http://localhost:8080/cocktail/hogehoge
